// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechFix.EntityModels;

#nullable disable

namespace TechFix.EntityModels.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230214032025_InitSeedData")]
    partial class InitSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TechFix.EntityModels.Category", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8064c62a-448c-4a92-bf0b-5087bd399ec5"),
                            IsDeleted = false,
                            Name = "LCD - Màn hình Laptop"
                        },
                        new
                        {
                            Id = new Guid("43b6c60d-960a-407a-aec3-a786527e7fd2"),
                            IsDeleted = false,
                            Name = "Màn hình AOC"
                        },
                        new
                        {
                            Id = new Guid("cd93fd2e-cf06-4893-b4a7-f01aa87cacb8"),
                            IsDeleted = false,
                            Name = "Phần mềm diệt virus - win"
                        },
                        new
                        {
                            Id = new Guid("cd6b794a-2bbd-4345-882a-55f2bea37f01"),
                            IsDeleted = false,
                            Name = "VGA Laptop"
                        },
                        new
                        {
                            Id = new Guid("d42d588d-e093-4241-a87b-57d39880e39d"),
                            IsDeleted = false,
                            Name = "CPU - Vi xử lý"
                        },
                        new
                        {
                            Id = new Guid("762315dc-3db1-4bb3-aec9-492300290ce2"),
                            IsDeleted = false,
                            Name = "ASUS"
                        },
                        new
                        {
                            Id = new Guid("ce55104e-1350-434f-b251-5c3d549c02fe"),
                            IsDeleted = false,
                            Name = "ACER"
                        },
                        new
                        {
                            Id = new Guid("97204ff0-9cac-4dee-86a4-57c71d1016cf"),
                            IsDeleted = false,
                            Name = "TOSHIBA"
                        },
                        new
                        {
                            Id = new Guid("065a68ed-a34e-4ae4-9b45-3b91f6742782"),
                            IsDeleted = false,
                            Name = "SONY"
                        },
                        new
                        {
                            Id = new Guid("33e8a1cd-a04b-4833-941b-b1cb8183d6ab"),
                            IsDeleted = false,
                            Name = "Macbook"
                        },
                        new
                        {
                            Id = new Guid("73a79910-c3ce-4cd6-a6e9-a48f4de8a727"),
                            IsDeleted = false,
                            Name = "Keo tản nhiệt"
                        });
                });

            modelBuilder.Entity("TechFix.EntityModels.Manufacturer", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e32e08d8-32d0-49a4-af6d-e9a8b02fa7ae"),
                            IsDeleted = false,
                            Name = "Pioneer"
                        },
                        new
                        {
                            Id = new Guid("3af759e8-b2e0-4b02-96b6-76c5609615f6"),
                            IsDeleted = false,
                            Name = "Colorful"
                        },
                        new
                        {
                            Id = new Guid("8657a192-250f-46f0-addc-0806460b4ea2"),
                            IsDeleted = false,
                            Name = "Pisen"
                        },
                        new
                        {
                            Id = new Guid("70f6af9a-9725-47c5-b9e3-66aecd85e47b"),
                            IsDeleted = false,
                            Name = "Newmen"
                        },
                        new
                        {
                            Id = new Guid("179f6f9c-33d7-4f43-8b36-b9668cba2cca"),
                            IsDeleted = false,
                            Name = "Genius"
                        },
                        new
                        {
                            Id = new Guid("f30a01bd-2a0c-4340-bfdb-6a497aecb648"),
                            IsDeleted = false,
                            Name = "HP"
                        },
                        new
                        {
                            Id = new Guid("242bf112-9304-4e64-a08a-f455cd132043"),
                            IsDeleted = false,
                            Name = "Unitek"
                        },
                        new
                        {
                            Id = new Guid("5834857c-c47f-4995-abd0-9919515d8b35"),
                            IsDeleted = false,
                            Name = "Energizer"
                        },
                        new
                        {
                            Id = new Guid("36aa5768-87aa-4b7a-9fc7-c8066d136c55"),
                            IsDeleted = false,
                            Name = "Western"
                        },
                        new
                        {
                            Id = new Guid("49747ba2-8a30-4bb5-a2a1-49d6580e672a"),
                            IsDeleted = false,
                            Name = "Addlink"
                        },
                        new
                        {
                            Id = new Guid("4ae0a384-443b-4901-85b1-cfa1976cf035"),
                            IsDeleted = false,
                            Name = "Caddy Bay"
                        },
                        new
                        {
                            Id = new Guid("45341e2d-7e0f-45e7-ad84-f361cd69dc41"),
                            IsDeleted = false,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = new Guid("b9ebb845-7dd3-4522-b2ba-5fc45f0459a0"),
                            IsDeleted = false,
                            Name = "Hoco"
                        },
                        new
                        {
                            Id = new Guid("d6eb32c3-1339-4b15-b6bf-db38a8bb04ee"),
                            IsDeleted = false,
                            Name = "Kingmax"
                        },
                        new
                        {
                            Id = new Guid("18eacb75-8d7f-4833-87d9-97ba3971a46e"),
                            IsDeleted = false,
                            Name = "Kingston"
                        },
                        new
                        {
                            Id = new Guid("151ecbb0-dbe5-4a80-ab56-e443e145b5e0"),
                            IsDeleted = false,
                            Name = "Seagate"
                        });
                });

            modelBuilder.Entity("TechFix.EntityModels.Product", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowNegativeSell")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInventoryTracking")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaximumNorm")
                        .HasColumnType("int");

                    b.Property<int>("MinimumNorm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalCost")
                        .HasPrecision(38, 16)
                        .HasColumnType("decimal(38,16)");

                    b.Property<Guid?>("ProductConditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SearchData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SellIn")
                        .HasPrecision(38, 16)
                        .HasColumnType("decimal(38,16)");

                    b.Property<decimal>("SellOut")
                        .HasPrecision(38, 16)
                        .HasColumnType("decimal(38,16)");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Warranty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ProductConditionId");

                    b.HasIndex("ProductUnitId");

                    b.HasIndex("StoreId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a86e7ce5-86ef-4eef-a5c8-86fd07388622"),
                            AllowNegativeSell = true,
                            Code = "SP0000010",
                            Description = "",
                            IsDeleted = false,
                            IsInventoryTracking = false,
                            ManufacturerId = new Guid("e32e08d8-32d0-49a4-af6d-e9a8b02fa7ae"),
                            MaximumNorm = 10,
                            MinimumNorm = 5,
                            Name = "Áo thun hai lỗ",
                            OriginalCost = 50000m,
                            ProductConditionId = new Guid("9420681a-6d03-45bb-ab59-bd1af9e3054a"),
                            Quantity = 5,
                            SellIn = 50000m,
                            SellOut = 70000m,
                            SupplierId = new Guid("196d3520-8ffd-49e5-b0f1-f88d4b5f1b59"),
                            Warranty = "Bảo hành 6Th"
                        },
                        new
                        {
                            Id = new Guid("8be4213c-68f4-49da-9232-08ee1c47c944"),
                            AllowNegativeSell = false,
                            Code = "SP000003",
                            Description = "",
                            IsDeleted = false,
                            IsInventoryTracking = true,
                            ManufacturerId = new Guid("3af759e8-b2e0-4b02-96b6-76c5609615f6"),
                            MaximumNorm = 0,
                            MinimumNorm = 0,
                            Name = "Cáp Pisen USB Type-C 3A 1m",
                            OriginalCost = 90000m,
                            ProductConditionId = new Guid("cb98afde-54ed-416c-a73c-18eef6f0983b"),
                            Quantity = 8,
                            SellIn = 90000m,
                            SellOut = 130000m,
                            SupplierId = new Guid("196d3520-8ffd-49e5-b0f1-f88d4b5f1b59"),
                            Warranty = "06TH"
                        },
                        new
                        {
                            Id = new Guid("3815f587-d474-4f9e-890e-02f4facb49d9"),
                            AllowNegativeSell = true,
                            Code = "SP0000011",
                            Description = "",
                            IsDeleted = false,
                            IsInventoryTracking = false,
                            ManufacturerId = new Guid("e32e08d8-32d0-49a4-af6d-e9a8b02fa7ae"),
                            MaximumNorm = 0,
                            MinimumNorm = 0,
                            Name = "Sạc dự phòng Pisen Color Power Pro 10000mAh đỏ-đen (Dual USB 1A/2.4A Smart)",
                            OriginalCost = 550000m,
                            ProductConditionId = new Guid("fcdf46b9-c1d6-4664-8ea4-7a1b25ab1875"),
                            Quantity = 0,
                            SellIn = 550000m,
                            SellOut = 650000m,
                            SupplierId = new Guid("196d3520-8ffd-49e5-b0f1-f88d4b5f1b59"),
                            Warranty = "12TH"
                        },
                        new
                        {
                            Id = new Guid("b936c681-c458-49d7-b4cb-0a9bfb760755"),
                            AllowNegativeSell = true,
                            Code = "SP0000022",
                            Description = "",
                            IsDeleted = false,
                            IsInventoryTracking = false,
                            ManufacturerId = new Guid("70f6af9a-9725-47c5-b9e3-66aecd85e47b"),
                            MaximumNorm = 5,
                            MinimumNorm = 3,
                            Name = "Chuột Newmen F300 không dây",
                            OriginalCost = 215000m,
                            ProductConditionId = new Guid("fcdf46b9-c1d6-4664-8ea4-7a1b25ab1875"),
                            Quantity = 3,
                            SellIn = 215000m,
                            SellOut = 270000m,
                            SupplierId = new Guid("196d3520-8ffd-49e5-b0f1-f88d4b5f1b59"),
                            Warranty = "12TH"
                        },
                        new
                        {
                            Id = new Guid("2c56968f-07c0-4f55-bbcd-fa6f0f0e40b7"),
                            AllowNegativeSell = true,
                            Code = "SP0000032",
                            Description = "",
                            IsDeleted = false,
                            IsInventoryTracking = true,
                            ManufacturerId = new Guid("e32e08d8-32d0-49a4-af6d-e9a8b02fa7ae"),
                            MaximumNorm = 5,
                            MinimumNorm = 1,
                            Name = "Caddybay mỏng 9.5mm Laptop",
                            OriginalCost = 35000m,
                            ProductConditionId = new Guid("fcdf46b9-c1d6-4664-8ea4-7a1b25ab1875"),
                            Quantity = 99,
                            SellIn = 35000m,
                            SellOut = 100000m,
                            SupplierId = new Guid("196d3520-8ffd-49e5-b0f1-f88d4b5f1b59"),
                            Warranty = "3TH"
                        },
                        new
                        {
                            Id = new Guid("2a34a331-95fd-4cd1-a77c-7a731c32e5b5"),
                            AllowNegativeSell = false,
                            Code = "SP0000041",
                            Description = "",
                            IsDeleted = true,
                            IsInventoryTracking = false,
                            ManufacturerId = new Guid("e32e08d8-32d0-49a4-af6d-e9a8b02fa7ae"),
                            MaximumNorm = 0,
                            MinimumNorm = 0,
                            Name = "SSD Pioneer APS-SL3N 120GB 2.5in ( Read 520MB/s - Write 400MB/s )",
                            OriginalCost = 440000m,
                            ProductConditionId = new Guid("fcdf46b9-c1d6-4664-8ea4-7a1b25ab1875"),
                            Quantity = 0,
                            SellIn = 440000m,
                            SellOut = 550000m,
                            SupplierId = new Guid("196d3520-8ffd-49e5-b0f1-f88d4b5f1b59"),
                            Warranty = "12TH"
                        });
                });

            modelBuilder.Entity("TechFix.EntityModels.ProductCondition", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductConditions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9420681a-6d03-45bb-ab59-bd1af9e3054a"),
                            IsDeleted = false,
                            Name = "Mới 100%"
                        },
                        new
                        {
                            Id = new Guid("cb98afde-54ed-416c-a73c-18eef6f0983b"),
                            IsDeleted = false,
                            Name = "Mới 99%"
                        },
                        new
                        {
                            Id = new Guid("fcdf46b9-c1d6-4664-8ea4-7a1b25ab1875"),
                            IsDeleted = false,
                            Name = "Mới 98%"
                        },
                        new
                        {
                            Id = new Guid("ba55e427-1ecd-4d44-a27a-a5be26b89fdd"),
                            IsDeleted = false,
                            Name = "Cũ đã qua sửa chữa"
                        },
                        new
                        {
                            Id = new Guid("de2d4f17-b82c-47c0-9a88-a7bae70c8579"),
                            IsDeleted = false,
                            Name = "Outlet"
                        },
                        new
                        {
                            Id = new Guid("f97327e2-d6aa-439f-991a-875460b45284"),
                            IsDeleted = false,
                            Name = "New Outlet"
                        });
                });

            modelBuilder.Entity("TechFix.EntityModels.ProductUnit", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductUnits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f5cbdec-b821-40f3-80c3-6b7ef1961e2b"),
                            IsDeleted = false,
                            Name = "Cái"
                        },
                        new
                        {
                            Id = new Guid("9c48ea71-07c4-4ec4-b1a1-5c6e07ece1e4"),
                            IsDeleted = false,
                            Name = "Bộ"
                        },
                        new
                        {
                            Id = new Guid("569b970a-b72f-4859-a2ed-8afbbf5d54b8"),
                            IsDeleted = false,
                            Name = "Con"
                        },
                        new
                        {
                            Id = new Guid("da4e1b1b-0c4d-444e-9e17-d9b98da66fc8"),
                            IsDeleted = false,
                            Name = "Cm"
                        });
                });

            modelBuilder.Entity("TechFix.EntityModels.Store", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("006e356b-8dc4-4d15-941f-eaa5e2432da0"),
                            Address = "",
                            IsDeleted = false,
                            Name = "TechFix",
                            Phone = "0123456778"
                        });
                });

            modelBuilder.Entity("TechFix.EntityModels.Supplier", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InDebt")
                        .HasPrecision(38, 16)
                        .HasColumnType("decimal(38,16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("196d3520-8ffd-49e5-b0f1-f88d4b5f1b59"),
                            Address = "",
                            Email = "",
                            InDebt = 0m,
                            IsDeleted = false,
                            Name = "NWH",
                            Note = "",
                            Phone = ""
                        },
                        new
                        {
                            Id = new Guid("33e3338c-7921-480a-89fe-c06eb62f0fd8"),
                            Address = "",
                            Email = "",
                            InDebt = 0m,
                            IsDeleted = false,
                            Name = "CTY PATECH",
                            Note = "",
                            Phone = ""
                        },
                        new
                        {
                            Id = new Guid("aabacf68-91af-4ea3-8402-0e7b77dc2d87"),
                            Address = "",
                            Email = "",
                            InDebt = 0m,
                            IsDeleted = false,
                            Name = "Chỉnh LK",
                            Note = "",
                            Phone = ""
                        },
                        new
                        {
                            Id = new Guid("0533febd-dec1-4593-90a9-5662eb6ff88b"),
                            Address = "",
                            Email = "",
                            InDebt = 0m,
                            IsDeleted = false,
                            Name = "Tấn Phát LTK",
                            Note = "",
                            Phone = ""
                        },
                        new
                        {
                            Id = new Guid("67fe282c-92e2-420b-a185-c92243131768"),
                            Address = "",
                            Email = "",
                            InDebt = 0m,
                            IsDeleted = false,
                            Name = "Chuẩn LTK",
                            Note = "",
                            Phone = ""
                        },
                        new
                        {
                            Id = new Guid("57294d71-1b0a-4b29-b3e3-c4de1f7fa16f"),
                            Address = "",
                            Email = "",
                            InDebt = 0m,
                            IsDeleted = false,
                            Name = "Duy Tân",
                            Note = "",
                            Phone = ""
                        },
                        new
                        {
                            Id = new Guid("f17bddcc-18fa-453f-b539-862f78b4f32e"),
                            Address = "",
                            Email = "",
                            InDebt = 0m,
                            IsDeleted = false,
                            Name = "Hải Việt",
                            Note = "",
                            Phone = ""
                        },
                        new
                        {
                            Id = new Guid("3e0adebb-5484-4a33-9436-e69532db5fee"),
                            Address = "",
                            Email = "",
                            InDebt = 0m,
                            IsDeleted = false,
                            Name = "LGT",
                            Note = "",
                            Phone = ""
                        },
                        new
                        {
                            Id = new Guid("e1d18951-2787-40d0-baec-ce0245aaa10f"),
                            Address = "",
                            Email = "",
                            InDebt = 0m,
                            IsDeleted = false,
                            Name = "Huy Phát Kingmater",
                            Note = "",
                            Phone = ""
                        },
                        new
                        {
                            Id = new Guid("8639f97d-06d3-415d-836b-52abe02394b9"),
                            Address = "",
                            Email = "",
                            InDebt = 0m,
                            IsDeleted = false,
                            Name = "Tuấn Hiền",
                            Note = "",
                            Phone = ""
                        },
                        new
                        {
                            Id = new Guid("f630391a-5c7e-4156-a2b1-d748ffe13a27"),
                            Address = "",
                            Email = "",
                            InDebt = 0m,
                            IsDeleted = false,
                            Name = "Văn Hải",
                            Note = "",
                            Phone = ""
                        },
                        new
                        {
                            Id = new Guid("1fed613e-a858-40a5-bd81-28844f482218"),
                            Address = "",
                            Email = "",
                            InDebt = 0m,
                            IsDeleted = false,
                            Name = "Phát Đạt LTK",
                            Note = "",
                            Phone = ""
                        });
                });

            modelBuilder.Entity("TechFix.EntityModels.User", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BonusPercent")
                        .HasPrecision(38, 16)
                        .HasColumnType("decimal(38,16)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TechFix.EntityModels.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SearchData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("TechFix.EntityModels.VlinkSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SequenceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VlinkSequence");
                });

            modelBuilder.Entity("TechFix.EntityModels.Product", b =>
                {
                    b.HasOne("TechFix.EntityModels.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("TechFix.EntityModels.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("TechFix.EntityModels.ProductCondition", "ProductCondition")
                        .WithMany()
                        .HasForeignKey("ProductConditionId");

                    b.HasOne("TechFix.EntityModels.ProductUnit", "ProductUnit")
                        .WithMany()
                        .HasForeignKey("ProductUnitId");

                    b.HasOne("TechFix.EntityModels.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId");

                    b.HasOne("TechFix.EntityModels.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");

                    b.Navigation("ProductCondition");

                    b.Navigation("ProductUnit");

                    b.Navigation("Store");

                    b.Navigation("Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
