export const GET_DANH_SACH_MAU = 'GET_DANH_SACH_MAU';
export const GET_DANH_SACH_MAU_SUCCESS = 'GET_DANH_SACH_MAU_SUCCESS';
export const GET_DANH_SACH_MAU_FAIL = 'GET_DANH_SACH_MAU_FAIL';

export const GET_PHIEU_TIEP_NHAN = 'GET_PHIEU_TIEP_NHAN';
export const GET_PHIEU_TIEP_NHAN_SUCCESS = 'GET_PHIEU_TIEP_NHAN_SUCCESS';
export const GET_PHIEU_TIEP_NHAN_FAIL = 'GET_PHIEU_TIEP_NHAN_FAIL';

export const GET_DETAIL_MAU = 'GET_DETAIL_MAU';
export const GET_DETAIL_MAU_SUCCESS = 'GET_DETAIL_MAU_SUCCESS';
export const GET_DETAIL_MAU_FAIL = 'GET_DETAIL_MAU_FAIL';

export const GET_LIST_PHIEU = 'GET_LIST_PHIEU';
export const GET_LIST_PHIEU_SUCCESS = 'GET_LIST_PHIEU_SUCCESS';
export const GET_LIST_PHIEU_FAIL = 'GET_LIST_PHIEU_FAIL';

export const GET_LIST_MAU_BY_PHIEU_TIEP_NHAN_ID = 'GET_LIST_MAU_BY_PHIEU_TIEP_NHAN_ID';
export const GET_LIST_MAU_BY_PHIEU_TIEP_NHAN_ID_SUCCESS = 'GET_LIST_MAU_BY_PHIEU_TIEP_NHAN_ID_SUCCESS';
export const GET_LIST_MAU_BY_PHIEU_TIEP_NHAN_ID_FAIL = 'GET_LIST_MAU_BY_PHIEU_TIEP_NHAN_ID_FAIL';

// ACTIONS
export const TOGGLE_CREATE_MAU = 'TOGGLE_CREATE_MAU';

export const GET_LIST_LINH_VUC = 'GET_LIST_LINH_VUC';
export const GET_LIST_LINH_VUC_SUCCESS = 'GET_LIST_LINH_VUC_SUCCESS';
export const GET_LIST_LINH_VUC_FAIL = 'GET_LIST_LINH_VUC_FAIL';

export const GET_CHI_TIEUS_GROUP_BY_LINHVUC = 'GET_CHI_TIEUS_GROUP_BY_LINHVUC';
export const GET_CHI_TIEUS_GROUP_BY_LINHVUC_SUCCESS = 'GET_CHI_TIEUS_GROUP_BY_LINHVUC_SUCCESS';
export const GET_CHI_TIEUS_GROUP_BY_LINHVUC_FAIL = 'GET_CHI_TIEUS_GROUP_BY_LINHVUC_FAIL';
