using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace TechFix.Common.Helper
{
    public class CountryHelper
    {
        public static string ConvertNameToCode(string countryName)
        {
            if (countryName == null)
                return "Other";
            var countryDic = GetCountryDic();
            if (countryDic.TryGetValue(countryName, out var countryCode))
            {
                return countryCode;
            }

            return "Other";
        }

        private static Dictionary<string, string> GetCountryDic()
        {
            return new Dictionary<string, string>
            {
                {"World", "001"},
                {"Afghanistan", "AF"},
                {"Albania", "AL"},
                {"United Arab Emirates", "AE"},
                {"Argentina", "AR"},
                {"Armenia", "AM"},
                {"Australia", "AU"},
                {"Austria", "AT"},
                {"Azerbaijan", "AZ"},
                {"Belgium", "BE"},
                {"Bangladesh", "BD"},
                {"Bulgaria", "BG"},
                {"Bahrain", "BH"},
                {"Bosnia & Herzegovina", "BA"},
                {"Belarus", "BY"},
                {"Belize", "BZ"},
                {"Bolivia", "BO"},
                {"Brazil", "BR"},
                {"Brunei", "BN"},
                {"Bhutan", "BT"},
                {"Botswana", "BW"},
                {"Canada", "CA"},
                {"Switzerland", "CH"},
                {"Chile", "CL"},
                {"China", "CN"},
                {"Côte d’Ivoire", "CI"},
                {"Cameroon", "CM"},
                {"Congo (DRC)", "CD"},
                {"Colombia", "CO"},
                {"Costa Rica", "CR"},
                {"Cuba", "CU"},
                {"Czechia", "CZ"},
                {"Germany", "DE"},
                {"Denmark", "DK"},
                {"Dominican Republic", "DO"},
                {"Algeria", "DZ"},
                {"Ecuador", "EC"},
                {"Egypt", "EG"},
                {"Eritrea", "ER"},
                {"Spain", "ES"},
                {"Estonia", "EE"},
                {"Ethiopia", "ET"},
                {"Finland", "FI"},
                {"France", "FR"},
                {"Faroe Islands", "FO"},
                {"United Kingdom", "GB"},
                {"Georgia", "GE"},
                {"Greece", "GR"},
                {"Greenland", "GL"},
                {"Guatemala", "GT"},
                {"Hong Kong SAR", "HK"},
                {"Honduras", "HN"},
                {"Croatia", "HR"},
                {"Haiti", "HT"},
                {"Hungary", "HU"},
                {"Indonesia", "ID"},
                {"India", "IN"},
                {"Ireland", "IE"},
                {"Iran", "IR"},
                {"Iraq", "IQ"},
                {"Iceland", "IS"},
                {"Israel", "IL"},
                {"Italy", "IT"},
                {"Jamaica", "JM"},
                {"Jordan", "JO"},
                {"Japan", "JP"},
                {"Kazakhstan", "KZ"},
                {"Kenya", "KE"},
                {"Kyrgyzstan", "KG"},
                {"Cambodia", "KH"},
                {"Korea", "KR"},
                {"Kuwait", "KW"},
                {"Laos", "LA"},
                {"Lebanon", "LB"},
                {"Libya", "LY"},
                {"Liechtenstein", "LI"},
                {"Sri Lanka", "LK"},
                {"Lithuania", "LT"},
                {"Luxembourg", "LU"},
                {"Latvia", "LV"},
                {"Macao SAR", "MO"},
                {"Morocco", "MA"},
                {"Monaco", "MC"},
                {"Moldova", "MD"},
                {"Maldives", "MV"},
                {"Mexico", "MX"},
                {"North Macedonia", "MK"},
                {"Mali", "ML"},
                {"Malta", "MT"},
                {"Myanmar", "MM"},
                {"Montenegro", "ME"},
                {"Mongolia", "MN"},
                {"Malaysia", "MY"},
                {"Nigeria", "NG"},
                {"Nicaragua", "NI"},
                {"Netherlands", "NL"},
                {"Norway", "NO"},
                {"Nepal", "NP"},
                {"New Zealand", "NZ"},
                {"Oman", "OM"},
                {"Pakistan", "PK"},
                {"Panama", "PA"},
                {"Peru", "PE"},
                {"Philippines", "PH"},
                {"Poland", "PL"},
                {"Puerto Rico", "PR"},
                {"Portugal", "PT"},
                {"Paraguay", "PY"},
                {"Qatar", "QA"},
                {"Réunion", "RE"},
                {"Romania", "RO"},
                {"Russia", "RU"},
                {"Rwanda", "RW"},
                {"Saudi Arabia", "SA"},
                {"Senegal", "SN"},
                {"Singapore", "SG"},
                {"El Salvador", "SV"},
                {"Somalia", "SO"},
                {"Serbia", "RS"},
                {"Slovakia", "SK"},
                {"Slovenia", "SI"},
                {"Sweden", "SE"},
                {"Syria", "SY"},
                {"Thailand", "TH"},
                {"Tajikistan", "TJ"},
                {"Turkmenistan", "TM"},
                {"Trinidad & Tobago", "TT"},
                {"Tunisia", "TN"},
                {"Turkey", "TR"},
                {"Taiwan", "TW"},
                {"Ukraine", "UA"},
                {"Uruguay", "UY"},
                {"United States", "US"},
                {"Uzbekistan", "UZ"},
                {"Venezuela", "VE"},
                {"Vietnam", "VN"},
                {"Yemen", "YE"},
                {"South Africa", "ZA"},
                {"Zimbabwe", "ZW"},

            };
        }
    }
}
