
// Action Types
export const SET_GLOBAL_LOADING = "SET_GLOBAL_LOADING";
export const VALIDATE_EULA = "VALIDATE_EULA";
export const VALIDATE_CRITICAL_MESSAGE = "VALIDATE_CRITICAL_MESSAGE";
export const VALIDATE_LANDING_PAGE = "VALIDATE_LANDING_PAGE";
export const CHANGE_RIBBON_ACTIONS = "CHANGE_RIBBON_ACTIONS";
export const SEARCH_CRITERIA = "SEARCH_CRITERIA";
export const FAVORITE_QUERIES = "FAVORITE_QUERIES";
export const FAVORITE_SHARED_QUERIES = "FAVORITE_SHARED_QUERIES";
export const FAVORITE_PRODUCTS = "FAVORITE_PRODUCTS";
export const FAVORITE_ASSETS = "FAVORITE_ASSETS";
export const FAVORITE_MEMBERS = "FAVORITE_MEMBERS";
export const SELECTED_KEY = "SELECTED_KEY";
export const TOGGLE_DETAIL = "TOGGLE_DETAIL";
export const INCONTAINER_DETAIL = "INCONTAINER_DETAIL";
export const TOGGLE_QUICKVIEW = "TOGGLE_QUICKVIEW";
export const UPDATE_SEARCH_CRITERIA = "UPDATE_SEARCH_CRITERIA";
export const UPDATE_LOGGING = "UPDATE_LOGGING";
export const LOGOUT = "LOGOUT";
export const SEARCH = "SEARCH"
export const REFRESH_GRID = "REFRESH_GRID"
export const RESET_STATE = "RESET_STATE"
